sonar.projectKey=Recruform
sonar.projectName=Recruform - LangGraph Resume Tailoring Agent
sonar.projectVersion=1.0

sonar.sources=agent,monitoring,prompts
sonar.tests=tests
sonar.language=py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc,output/**,logs/**,input/**

sonar.host.url=http://host.docker.internal:9000
sonar.token=squ_be61cca2b72e25947ae6a5f6349605848a36499b
